build:
  image: python:2.7
  script:
  - pip install sphinx sphinx-bootstrap-theme robpol86-sphinxcontrib-googleanalytics
  - sphinx-build . public

  artifacts:
    paths:
      - public

deploy:
  type: deploy
  image: docker:latest

  variables:
    DOCKER_DRIVER: overlay2

  services:
  - docker:dind

  script:
  - docker info
